### ISSUE TITLE
Simply not working. java.lang.IllegalAccessError.

### ISSUE THREAD

**Issue by promlgxd** [TownyAdvanced/WorldGuard-Towny#1]
**Describe the bug**
Console drops an error when doing a town inside a world guard region and, in fact, it does not work. The town is created and overrides the region.
**To Reproduce**
1. Go to the "Spawn" (in this case) region.
2. Try to set up the flag. Does not work.
-----------------------------------------------------
1. Go to the "Spawn" (in this case) region.
2. Do /t new <name> and /confirm. The town is created.

**Expected behavior**
1. Go to the "Spawn" (in this case) region.
2. Setting the town-creation flag succesfully.
------------------------------------------------------
1. Go to the "Spawn" (in this case) region.
2. Do /t new <name> and being restricted to do so.
**Additional context**
*INFO:*
CONSOLE ERROR - https://pastebin.com/5JdcBFGL
TOWNY VERSION - 0.96.1.1.0 - 1.12.2 - SNAPSHOT 2
WORLDGUARD-TOWNY VERSION - 1.1.0
SERVER - Akarin version git-Akarin-5fe9361 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
MC VERSION - 1.12.2

**Additional info**
I don't know if this has something to do, but I just wanted to add I'm using FastAsyncWorldEdit along with the normal WorldEdit.

**Comment by suneettipirneni** [comment]
Thanks I’ll look into this

**Comment by ghost** [comment]
There may be compatibility issues with 1.12 as the plugin only existed after 1.14.4 was out

**Comment by promlgxd** [comment]
Oh, then what could I do to prevent town creation in worldguard regions? Is there any other thing I can try?

**Comment by ghost** [comment]
> Oh, then what could I do to prevent town creation in worldguard regions? Is there any other thing I can try?

Yeah you can create a town and set the mayor of the town as an npc, so nobody can claim that area.

**Comment by promlgxd** [comment]
Would citizens let me do that? If so, how? I've got 0 experience with npc plugins to be honest.

**Comment by LlmDl** [comment]
Towny has a `/ta set mayor TOWNNAME npc` command that will make it an NPC town, no other plugins required.

**Comment by promlgxd** [comment]
Sorry , what is the command to remove the upkeep from a nation/town? It's to remove it before setting it as an NPC town for it to not disband.

**Comment by LlmDl** [comment]
Towny doesn't charge upkeep on towns/nation that are controlled by an NPC mayor/king.
