### ISSUE TITLE
New flags: friendly-fire, pvp

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/WorldGuard-Towny#4]
**Is your feature request related to a problem? Please describe.**
I need to create a zone with pvp thats not an Arena type plot and wich shape is not a whole town block. I need a worldguard flag to override friendly-fire and also one to forcepvp in a non-pvp town (like how arena plot does but so i can use it with specific shapes that are not town blocks)

**Describe the solution you'd like**
Addition of 2 flags:
towny_friendlyfire
towny_pvpoverride (using the usual pvp allow flag that comes with wg doesnt work, towny prevents the pvp anyways)

**Comment by LlmDl** [comment]
This is doable via the API using the TownyPlayerDamagePlayerEvent and TownyFriendlyFireTestEvent events.

**Comment by ElMoha943** [comment]
> This is doable via the API using the TownyPlayerDamagePlayerEvent and TownyFriendlyFireTestEvent events.

meaning i need a custom plugin for it?

**Comment by LlmDl** [comment]
Yes you can accomplish it with a separate plugin. Or if you'd like you can make a Pull Request with the changes to this repo.
